use std::rc::Rc;
use std::time::Duration;

use crate::PajamaxService;

/// Configured server. Used to start the server.
///
/// Generated by [`Config::add_service`].
///
/// # Examples
///
/// ```
/// pajamax::Config::new()
///     .max_concurrent_connections(2000)
///     .add_service(GreeterServer::new(greeter))   // return ConfigedServer
///     .add_service(Greeter2Server::new(greeter2)) // add more services
///     .serve(addr)  // start the server!
///     .unwrap();
/// ```
pub struct ConfigedServer {
    pub(crate) config: Config,
    pub(crate) services: Vec<Box<dyn Fn() -> Rc<dyn PajamaxService> + Send + Sync>>,
}

impl ConfigedServer {
    /// Add more services.
    pub fn add_service<S, F>(mut self, factory: F) -> Self
    where
        F: Fn() -> S + Send + Sync + 'static,
        S: PajamaxService + 'static,
    {
        self.services.push(Box::new(move || Rc::new(factory())));
        self
    }

    /// Start a listener on the current compio runtime.
    ///
    /// This is an async function that must be called from within a compio runtime.
    /// The caller is responsible for creating compio runtimes and threads.
    pub async fn listen(self, addr: &str) -> std::io::Result<()> {
        let services: Vec<Rc<dyn crate::PajamaxService>> =
            self.services.iter().map(|f| f()).collect();
        crate::connection::accept_loop(services, self.config, addr.to_string()).await
    }

    /// Start the server with built-in thread-per-core compio runtimes.
    ///
    /// Convenience method that creates compio runtimes and blocks the calling thread.
    pub fn serve(self, addr: &str) -> std::io::Result<()> {
        crate::connection::serve_with_config(self.services, self.config, addr.to_string())
    }
}

/// Configure the server.
#[derive(Clone, Copy, Debug)]
#[allow(dead_code)]
pub struct Config {
    pub(crate) max_concurrent_connections: usize,
    pub(crate) max_concurrent_streams: usize,
    pub(crate) max_frame_size: usize,
    pub(crate) max_flush_requests: usize,
    pub(crate) max_flush_size: usize,
    pub(crate) idle_timeout: Duration,
    pub(crate) write_timeout: Duration,
    pub(crate) num_cores: usize,
}

impl Config {
    /// Create a default configuration.
    pub fn new() -> Self {
        Self {
            max_concurrent_connections: 100,
            max_concurrent_streams: 1000,
            max_frame_size: 16 * 1024,
            max_flush_requests: 50,
            max_flush_size: 15000,
            idle_timeout: Duration::from_secs(60),
            write_timeout: Duration::from_secs(10),
            num_cores: 1,
        }
    }

    pub fn max_concurrent_connections(self, n: usize) -> Self {
        Self {
            max_concurrent_connections: n,
            ..self
        }
    }

    pub fn max_concurrent_streams(self, n: usize) -> Self {
        Self {
            max_concurrent_streams: n,
            ..self
        }
    }

    pub fn max_frame_size(self, n: usize) -> Self {
        Self {
            max_frame_size: n,
            ..self
        }
    }

    pub fn max_flush_requests(self, n: usize) -> Self {
        Self {
            max_flush_requests: n,
            ..self
        }
    }

    pub fn max_flush_size(self, n: usize) -> Self {
        Self {
            max_flush_size: n,
            ..self
        }
    }

    pub fn idle_timeout(self, d: Duration) -> Self {
        Self {
            idle_timeout: d,
            ..self
        }
    }

    pub fn write_timeout(self, d: Duration) -> Self {
        Self {
            write_timeout: d,
            ..self
        }
    }

    /// Number of cores to use (thread-per-core model).
    /// Default: 1
    pub fn num_cores(self, n: usize) -> Self {
        Self {
            num_cores: n,
            ..self
        }
    }

    /// Add the first service, and return a ConfigedServer.
    pub fn add_service<S, F>(self, factory: F) -> ConfigedServer
    where
        F: Fn() -> S + Send + Sync + 'static,
        S: PajamaxService + 'static,
    {
        ConfigedServer {
            config: self,
            services: vec![Box::new(move || Rc::new(factory()))],
        }
    }
}
